version: "3.9"
services:
  java_db:
    container_name: java_db
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 123
      MARIADB_DATABASE: usersCrud
      MARIADB_USER: usuario
      MARIADB_PASSWORD: 123

  java_app:
    container_name: java_app
    image: crud-java:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: java_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123
      DB_NAME: usersCrud
      DB_DRIVER: org.mariadb.jdbc.Driver
      DB_DIALECT: org.jooq.impl.MariaDBDialect
      DB_SCHEMA: public
    links:
      - java_db
    depends_on:
      - java_db
